version: '3'

services:
  redis:
    image: redis
    ports:
      - 6379:6379

  dgraph:
    image: dgraph/standalone:v20.03.0
    volumes:
      - dgraph:/dgraph
    ports:
      - 8080:8080
      - 9080:9080
      - 8000:8000
    

volumes:
  dgraph: {}
